# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'DOS-Monster' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DOS-Monster
  pod 'SwiftLint'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxAppState'

  target 'DOS-MonsterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DOS-MonsterUITests' do
    # Pods for testing
  end

end
